PRAGMA foreign_key = ON;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    UserID INTEGER PRIMARY KEY,
    UserName VARCHAR NOT NULL,
    PW VARBINARY NOT NULL
);

DROP TABLE IF EXISTS roles;
CREATE TABLE roles (
    RoleID INTEGER PRIMARY KEY,
    RoleName VARCHAR
);

DROP TABLE IF EXISTS userRole;
CREATE TABLE userRole (
    UserID INTEGER,
    RoleID INTEGER,
    PRIMARY KEY (UserID,RoleID)
    CONSTRAINT fk_users FOREIGN KEY (UserID) REFERENCES users(UserID)
    CONSTRAINT fk_roles FOREIGN KEY (RoleID) REFERENCES roles(RoleID)
);
COMMIT;